version: "3.7"
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    env_file:
      - .env

volumes:
  mysql: